services:
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: secret
        volumes:
            - mongodb_data:/data/db

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        ports:
            - '8081:8081'
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin # 👈 match MongoDB user
            ME_CONFIG_MONGODB_ADMINPASSWORD: secret # 👈 match MongoDB password
            ME_CONFIG_BASICAUTH_USERNAME: express # optional: web UI login
            ME_CONFIG_BASICAUTH_PASSWORD: express123 # optional: web UI login
        depends_on:
            - mongodb

volumes:
    mongodb_data:
